name: Deploy Streamlit App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso de depuración para verificar las variables
      - name: Debug Secrets
        run: |
          echo "API_KEY=$API_KEY"
          echo "HOST=$HOST"
          echo "USER=$USER"
          echo "PASSWORD=$PASSWORD"
          echo "DATABASE=$DATABASE"
        env:
          API_KEY: ${{ secrets.API_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE: ${{ secrets.DATABASE }}

      - name: Run Streamlit
        env:
          API_KEY: ${{ secrets.API_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE: ${{ secrets.DATABASE }}
        run: |
          streamlit run app.py


